### ISSUE TITLE
ENOENT error trying to build on windows

### ISSUE THREAD

**Issue by dpastoor** [imagemin/imagemin-app#14]
FYI, errors out using powershell due to touch command in the make file, might be worth noting in readme to use something like cygwin to get around that.

Error portion:

```
imagemin@1.0.5 node_modules\imagemin
├── get-stdin@3.0.2
├── stat-mode@0.2.1
├── ware@0.3.0
├── nopt@3.0.1 (abbrev@1.0.5)
├── tempfile@1.1.1 (os-tmpdir@1.0.0, uuid@2.0.1)
├── fs-extra@0.11.1 (jsonfile@2.0.0, ncp@0.6.0, mkdirp@0.5.0, rimraf@2.3.3)
├── imagemin-svgo@1.0.2 (is-svg@1.1.1, svgo@0.4.5)
├── imagemin-jpegtran@1.0.0 (is-jpg@1.0.0, exec-buffer@1.1.2, jpegtran-bin@1.0.2)
├── imagemin-optipng@1.0.0 (is-png@1.0.0, exec-buffer@1.1.2, optipng-bin@1.0.1)
├── imagemin-pngquant@1.0.2 (is-png@1.0.0, exec-buffer@1.1.2, pngquant-bin@1.0.1)
└── imagemin-gifsicle@1.0.0 (is-gif@1.0.0, exec-buffer@1.1.2, gifsicle@1.0.3)
make[1]: Entering directory `C:/Users/devin/Documents/Repos/imagemin-app'
make[2]: Entering directory `C:/Users/devin/Documents/Repos/imagemin-app'
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn C:\Users\devin\Documents\Repos\imagemin-app\node_modules\duo\node_modules\gnode\bin\gnode ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
make[2]: Leaving directory `C:/Users/devin/Documents/Repos/imagemin-app'
make[2]: Entering directory `C:/Users/devin/Documents/Repos/imagemin-app'
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn C:\Users\devin\Documents\Repos\imagemin-app\node_modules\duo\node_modules\gnode\bin\gnode ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
make[2]: Leaving directory `C:/Users/devin/Documents/Repos/imagemin-app'
make[1]: Leaving directory `C:/Users/devin/Documents/Repos/imagemin-app'
```

Stuff that works (above error)
```

> spawn-sync@1.0.6 postinstall C:\Users\devin\Documents\Repos\imagemin-app\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle\node_modules\bin-wrapper\node_modules\bin-check\node_modules\spawn-sync
> node postinstall


> spawn-sync@1.0.6 postinstall C:\Users\devin\Documents\Repos\imagemin-app\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin\node_modules\bin-wrapper\node_modules\bin-check\node_modules\spawn-sync
> node postinstall


> spawn-sync@1.0.6 postinstall C:\Users\devin\Documents\Repos\imagemin-app\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin\node_modules\bin-wrapper\node_modules\bin-check\node_modules\spawn-sync
> node postinstall


> spawn-sync@1.0.6 postinstall C:\Users\devin\Documents\Repos\imagemin-app\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin\node_modules\bin-wrapper\node_modules\bin-check\node_modules\spawn-sync
> node postinstall


> jpegtran-bin@1.0.2 postinstall C:\Users\devin\Documents\Repos\imagemin-app\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

     fetch : https://raw.github.com/imagemin/jpegtran-bin/v1.0.2/vendor/win/x64/jpegtran.exe
     fetch : https://raw.github.com/imagemin/jpegtran-bin/v1.0.2/vendor/win/x64/libjpeg-62.dll




√ pre-build test passed successfully!

> optipng-bin@1.0.1 postinstall C:\Users\devin\Documents\Repos\imagemin-app\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js

     fetch : https://raw.github.com/imagemin/optipng-bin/v1.0.1/vendor/win/optipng.exe


√ pre-build test passed successfully!

> pngquant-bin@1.0.1 postinstall C:\Users\devin\Documents\Repos\imagemin-app\node_modules\imagemin\node_modules\imagemin-pngquant\node_modules\pngquant-bin
> node lib/install.js

     fetch : https://raw.github.com/imagemin/pngquant-bin/v1.0.1/vendor/win/pngquant.exe


√ pre-build test passed successfully!

> gifsicle@1.0.3 postinstall C:\Users\devin\Documents\Repos\imagemin-app\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle
> node lib/install.js

     fetch : https://raw.github.com/imagemin/gifsicle-bin/v1.0.3/vendor/win/x64/gifsicle.exe


√ pre-build test passed successfully!
object-assign@1.0.0 node_modules\object-assign

each-async@1.1.1 node_modules\each-async
├── set-immediate-shim@1.0.1
└── onetime@1.0.0

clean-css@2.2.23 node_modules\clean-css
└── commander@2.2.0

uglify-js@2.4.21 node_modules\uglify-js
├── uglify-to-browserify@1.0.2
├── async@0.2.10
├── yargs@3.5.4 (camelcase@1.0.2, decamelize@1.0.0, window-size@0.1.0, wordwrap@0.0.2)
└── source-map@0.1.34 (amdefine@0.1.0)

duo@0.7.7 node_modules\duo
├── get-stdin@1.0.0
├── unyield@0.0.1
├── co-exists@0.0.1
├── co@3.1.0
├── stream-log@0.1.0
├── bytes@1.0.0
├── debug@0.7.4
├── thunkify@2.1.2
├── delegates@0.0.3
├── cp@0.1.1
├── extend.js@0.0.1
├── batch@0.5.2
├── step.js@2.0.5
├── win-fork@1.1.1
├── archy@0.0.2
├── read-file-stdin@0.0.4 (stream-to-array@1.0.0)
├── atomic-json@0.0.4 (enqueue@0.0.3)
├── duo-string-to-js@0.1.0 (string-to-js@0.0.1)
├── co-parallel@1.0.0 (co-thread@0.0.1)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── file-deps@0.0.5 (mini-tokenizer@0.1.2)
├── json-mask@0.3.4
├── mkdirp@0.5.0 (minimist@0.0.8)
├── co-fs@1.2.0 (thunkify@0.0.1, co-from-stream@0.0.0)
├── component-clone@0.2.2 (component-type@1.1.0)
├── max-component@1.0.0 (to-function@2.0.6)
├── concat-stream@1.4.8 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
├── language-classifier@0.0.1 (classifier@0.1.0)
├── stream-to-array@2.0.2 (native-or-bluebird@1.2.0, bluebird@2.9.25)
├── duo-watch@0.1.1 (debug@1.0.4, minimatch@1.0.0, sane@0.5.4)
├── duo-main@0.0.3 (component-type@1.1.0, mocha@1.21.5)
├── duo-package@0.4.2 (thunkify@0.0.1, debug@0.8.1, node-netrc@0.0.1, enstore@0.0.2, semver@2.3.2, gh-resolve@3.1.0, tar-fs@0.4.1, request@2.55.0)
├── gnode@0.0.8 (regenerator@0.8.22)
├── duo-pack@1.0.12 (combine-source-map@0.4.0, gnode@0.1.1)
└── duo-test@0.3.13 (incasesensitive@1.0.0, buffer-events@0.0.2, co-exec@1.1.0, open@0.0.5, wd-browser@1.1.0, co-timeout@0.1.0, koa-route@1.1.4, debug@1.0.4, queue-component@1.0.6, koa-static@1.4.9, koa@0.8.2, to-pascal-case@0.0.2, mocha@1.21.5, localtunnel@1.5.0, gnode@0.1.1, wd@0.3.11)

myth@1.4.0 node_modules\myth
├── rework-custom-media@0.1.1
├── is-browser@2.0.1
├── pad-component@0.0.1
├── node-watch@0.3.4
├── write-file-stdout@0.0.2
├── rework-rebeccapurple@1.0.1
├── rework-font-variant@1.0.1
├── colors@0.6.2
├── rework-hex-alpha@1.0.0 (rgb@0.0.1)
├── rework-vars@3.1.1 (rework-visit@1.0.0, balanced-match@0.1.0)
├── rework-calc@1.1.0 (rework-visit@1.0.0, balanced-match@0.1.0)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── read-file-stdin@0.2.0 (gather-stream@1.0.0)
├── clone-component@0.2.2 (component-type@1.1.0)
├── to-space-case@0.1.3 (to-no-case@0.1.2)
├── rework-color-function@1.2.1 (balanced-match@0.0.0, css-color-function@1.2.1)
├── to-slug-case@0.1.2 (to-space-case@0.1.2)
├── rework-import@1.2.1 (parse-import@0.1.3, find-file@0.1.4, css@2.2.0)
├── rework@1.0.1 (convert-source-map@0.3.5, css@2.2.0)
└── autoprefixer-core@3.1.2 (postcss@2.2.6, caniuse-db@1.0.30000161)
```

**Comment by kevva** [comment]
We are rewriting this so the old stuff might not be working.

**Comment by dpastoor** [comment]
ah cool! thanks

**Comment by ezraroi** [comment]
any updates on this? currently we can not use grunt-contrib-imagemin anymore

**Comment by kevva** [comment]
@ezraroi, how is this related to `grunt-contrib-imagemin`?

**Comment by ezraroi** [comment]
yes @kevva

**Comment by ezraroi** [comment]
it is breaking it as it is using this tool @kevva

**Comment by Rowno** [comment]
@ezraroi I think you're talking about https://github.com/imagemin/imagemin

**Comment by ezraroi** [comment]
sorry
